name: Ping Supabase to Prevent Pausing

on:
  schedule:
    - cron: '0 0 * * 3' # Runs at 12:00 AM every Wednesday

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install @supabase/supabase-js

      - name: Ping Supabase
        env:
          SUPABASE_URL: https://sqvelnvvyapcyvkpuimq.supabase.co
          SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxdmVsbnZ2eWFwY3l2a3B1aW1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDg4NDYwNzcsImV4cCI6MjAyNDQyMjA3N30.brKM1BCQKj964spaTYQ0yYYifFViPgcQvHSZu_ziKOs
        run: |
          node -e "
          const { createClient } = require('@supabase/supabase-js');
          const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);
          supabase.from('shoes').select('id').limit(1).then(console.log).catch(console.error);
          "
